{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "vclass.serviceAccountName" . }}
  labels:
{{ include "vclass.labels" . | indent 4 }}
{{- end -}}
