{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "vcpe.serviceAccountName" . }}
  labels:
{{ include "vcpe.labels" . | indent 4 }}
{{- end -}}
