apiVersion: v1
kind: Service
metadata:
  name: {{ include "vcpe.fullname" . }}
  labels:
{{ include "vcpe.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports: {}
  selector:
    app.kubernetes.io/name: {{ include "vcpe.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
